[rospy.client][INFO] 2017-08-14 09:05:54,938: init_node, name[/bebop/fence], pid[67]
[xmlrpc][INFO] 2017-08-14 09:05:54,939: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-08-14 09:05:54,940: Started XML-RPC server [http://192.168.201.36:37175/]
[rospy.init][INFO] 2017-08-14 09:05:54,940: ROS Slave URI: [http://192.168.201.36:37175/]
[rospy.impl.masterslave][INFO] 2017-08-14 09:05:54,940: _ready: http://192.168.201.36:37175/
[rospy.registration][INFO] 2017-08-14 09:05:54,941: Registering with master node http://192.168.201.4:11311
[xmlrpc][INFO] 2017-08-14 09:05:54,941: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-08-14 09:05:55,041: registered with master
[rospy.rosout][INFO] 2017-08-14 09:05:55,041: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 09:05:55,045: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 09:05:55,048: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 09:05:55,095: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,124: topic[/bebop/stop] adding connection to [/bebop/path_controller], count 1
[rospy.internal][INFO] 2017-08-14 09:05:55,159: topic[/tf] adding connection to [http://192.168.201.36:38139/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,228: topic[/bebop/takeoff_input] adding connection to [http://192.168.201.36:37699/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,229: topic[/bebop/cmd_vel_input] adding connection to [http://192.168.201.36:37699/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,234: topic[/bebop/land] adding connection to [http://192.168.201.36:37699/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,238: topic[/bebop/mocap_odom] adding connection to [http://192.168.201.36:38139/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,240: topic[/bebop/land] adding connection to [http://192.168.201.36:37175/], count 1
[rospy.internal][INFO] 2017-08-14 09:05:55,242: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,247: topic[/bebop/target] adding connection to [http://192.168.201.36:35766/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,260: topic[/bebop/des_vel] adding connection to [http://192.168.201.36:35766/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,265: topic[/bebop/enable_tracking] adding connection to [http://192.168.201.36:37699/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,272: topic[/head/mocap_odom] adding connection to [http://192.168.201.36:38139/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,291: topic[/bebop/observe] adding connection to [http://192.168.201.36:37699/], count 0
[rospy.internal][INFO] 2017-08-14 09:05:55,299: topic[/bebop/stop_observe] adding connection to [http://192.168.201.36:37699/], count 0
[rosout][INFO] 2017-08-14 09:05:55,300: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 09:05:55,328: Started SimpleActionServer fence_control
[rospy.internal][INFO] 2017-08-14 09:05:55,341: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-08-14 09:06:24,692: topic[/diagnostics] adding connection to [/rqt_gui_py_node_12527], count 0
[rospy.internal][INFO] 2017-08-14 09:06:25,361: topic[/bebop/fence/parameter_descriptions] adding connection to [/rqt_gui_py_node_12527], count 0
[rospy.internal][INFO] 2017-08-14 09:06:25,367: topic[/bebop/fence/parameter_updates] adding connection to [/rqt_gui_py_node_12527], count 0
[rosout][INFO] 2017-08-14 09:07:01,701: Controller has received landing
[rospy.core][INFO] 2017-08-14 09:07:46,156: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 09:07:46,203: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 09:07:46,204: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 09:07:46,205: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 09:07:46,207: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 09:07:46,208: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 09:07:46,210: Unable to initiate TCP/IP socket to 192.168.201.36:45857 (http://192.168.201.36:37699/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 09:07:46,210: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][ERROR] 2017-08-14 09:07:46,211: Unable to initiate TCP/IP socket to 192.168.201.36:39349 (http://192.168.201.36:37175/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 09:07:46,212: topic[/bebop/fence/parameter_descriptions] removing connection to /rqt_gui_py_node_12527
[rospy.internal][INFO] 2017-08-14 09:07:46,212: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-08-14 09:07:46,213: topic[/bebop/fence/parameter_updates] removing connection to /rqt_gui_py_node_12527
[rospy.internal][INFO] 2017-08-14 09:07:46,214: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 09:07:46,214: topic[/bebop/stop] removing connection to /bebop/path_controller
[rospy.internal][INFO] 2017-08-14 09:07:46,215: topic[/diagnostics] removing connection to /rqt_gui_py_node_12527
[rospy.internal][WARNING] 2017-08-14 09:07:46,216: Unknown error initiating TCP/IP socket to 192.168.201.36:55813 (http://192.168.201.36:38139/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-08-14 09:07:46,216: topic[/bebop/mocap_odom] removing connection to http://192.168.201.36:38139/
[rospy.topics][ERROR] 2017-08-14 09:07:46,218: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 820, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-08-14 09:07:46,218: topic[/bebop/land] removing connection to http://192.168.201.36:37699/
[rospy.internal][INFO] 2017-08-14 09:07:46,218: topic[/bebop/land] removing connection to http://192.168.201.36:37175/
[rospy.internal][INFO] 2017-08-14 09:07:46,219: topic[/bebop/des_vel] removing connection to http://192.168.201.36:35766/
[rospy.internal][INFO] 2017-08-14 09:07:46,219: topic[/bebop/target] removing connection to http://192.168.201.36:35766/
[rospy.internal][INFO] 2017-08-14 09:07:46,219: topic[/head/mocap_odom] removing connection to http://192.168.201.36:38139/
[rospy.internal][INFO] 2017-08-14 09:07:46,220: topic[/tf] removing connection to http://192.168.201.36:38139/
[rospy.internal][INFO] 2017-08-14 09:07:46,220: topic[/bebop/takeoff_input] removing connection to http://192.168.201.36:37699/
[rospy.internal][INFO] 2017-08-14 09:07:46,220: topic[/bebop/cmd_vel_input] removing connection to http://192.168.201.36:37699/
[rospy.internal][INFO] 2017-08-14 09:07:46,221: topic[/bebop/stop_observe] removing connection to http://192.168.201.36:37699/
[rospy.internal][INFO] 2017-08-14 09:07:46,221: topic[/bebop/observe] removing connection to http://192.168.201.36:37699/
[rospy.internal][INFO] 2017-08-14 09:07:46,221: topic[/bebop/enable_tracking] removing connection to http://192.168.201.36:37699/
[rospy.impl.masterslave][INFO] 2017-08-14 09:07:46,221: signal-2
[rospy.client][INFO] 2017-08-14 09:08:10,519: init_node, name[/bebop/fence], pid[67]
[xmlrpc][INFO] 2017-08-14 09:08:10,520: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-08-14 09:08:10,522: ROS Slave URI: [http://192.168.201.36:46766/]
[xmlrpc][INFO] 2017-08-14 09:08:10,522: Started XML-RPC server [http://192.168.201.36:46766/]
[rospy.impl.masterslave][INFO] 2017-08-14 09:08:10,523: _ready: http://192.168.201.36:46766/
[rospy.registration][INFO] 2017-08-14 09:08:10,525: Registering with master node http://192.168.201.4:11311
[xmlrpc][INFO] 2017-08-14 09:08:10,529: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-08-14 09:08:10,625: registered with master
[rospy.rosout][INFO] 2017-08-14 09:08:10,628: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 09:08:10,631: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 09:08:10,633: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 09:08:10,654: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,694: topic[/bebop/stop] adding connection to [/bebop/path_controller], count 1
[rospy.internal][INFO] 2017-08-14 09:08:10,758: topic[/tf_static] adding connection to [http://192.168.201.36:37639/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,760: topic[/tf] adding connection to [http://192.168.201.36:33899/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,763: topic[/tf] adding connection to [http://192.168.201.36:37639/], count 1
[rospy.internal][INFO] 2017-08-14 09:08:10,827: topic[/bebop/cmd_vel_input] adding connection to [http://192.168.201.36:42992/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,828: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,837: topic[/bebop/land] adding connection to [http://192.168.201.36:41884/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,842: topic[/bebop/land] adding connection to [http://192.168.201.36:42992/], count 1
[rospy.internal][INFO] 2017-08-14 09:08:10,845: topic[/bebop/takeoff_input] adding connection to [http://192.168.201.36:42992/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,850: topic[/bebop/land] adding connection to [http://192.168.201.36:46766/], count 2
[rosout][INFO] 2017-08-14 09:08:10,846: Controller has received landing
[rospy.internal][INFO] 2017-08-14 09:08:10,853: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,858: topic[/bebop/mocap_odom] adding connection to [http://192.168.201.36:33899/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,869: topic[/bebop/target] adding connection to [http://192.168.201.36:41810/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,876: topic[/bebop/fence/parameter_updates] adding connection to [/rqt_gui_py_node_12527], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,879: topic[/bebop/fence/parameter_descriptions] adding connection to [/rqt_gui_py_node_12527], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,887: topic[/bebop/des_vel] adding connection to [http://192.168.201.36:41810/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,887: topic[/diagnostics] adding connection to [/rqt_gui_py_node_12527], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,891: topic[/bebop/enable_tracking] adding connection to [http://192.168.201.36:42992/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,896: topic[/head/mocap_odom] adding connection to [http://192.168.201.36:33899/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,900: topic[/bebop/states/common/CommonState/BatteryStateChanged] adding connection to [http://192.168.201.36:42302/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,916: topic[/bebop/observe] adding connection to [http://192.168.201.36:42992/], count 0
[rospy.internal][INFO] 2017-08-14 09:08:10,924: topic[/bebop/stop_observe] adding connection to [http://192.168.201.36:42992/], count 0
[rosout][INFO] 2017-08-14 09:08:10,930: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 09:08:10,967: Started SimpleActionServer fence_control
[rospy.internal][ERROR] 2017-08-14 09:08:11,745: Unable to initiate TCP/IP socket to 192.168.201.36:43383 (http://192.168.201.36:41884/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-08-14 09:08:12,748: Unknown error initiating TCP/IP socket to 192.168.201.36:43383 (http://192.168.201.36:41884/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-08-14 09:08:12,748: topic[/bebop/land] removing connection to http://192.168.201.36:41884/
[rospy.internal][WARNING] 2017-08-14 09:08:16,494: Unknown error initiating TCP/IP socket to 192.168.201.36:60699 (http://192.168.201.36:42302/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-08-14 09:08:16,495: topic[/bebop/states/common/CommonState/BatteryStateChanged] removing connection to http://192.168.201.36:42302/
[rospy.internal][WARNING] 2017-08-14 09:08:53,688: Unknown error initiating TCP/IP socket to 192.168.201.36:43827 (http://192.168.201.36:37639/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2017-08-14 09:08:53,689: Unknown error initiating TCP/IP socket to 192.168.201.36:43827 (http://192.168.201.36:37639/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-08-14 09:08:53,689: topic[/tf] removing connection to http://192.168.201.36:37639/
[rospy.internal][INFO] 2017-08-14 09:08:53,690: topic[/tf_static] removing connection to http://192.168.201.36:37639/
[rospy.internal][INFO] 2017-08-14 09:09:06,524: topic[/tf_static] adding connection to [http://192.168.201.36:35449/], count 0
[rospy.internal][INFO] 2017-08-14 09:09:06,525: topic[/tf] adding connection to [http://192.168.201.36:35449/], count 1
[rospy.internal][INFO] 2017-08-14 09:09:06,640: topic[/bebop/states/common/CommonState/BatteryStateChanged] adding connection to [http://192.168.201.36:36960/], count 0
[rospy.internal][WARNING] 2017-08-14 09:09:12,768: Unknown error initiating TCP/IP socket to 192.168.201.36:34842 (http://192.168.201.36:36960/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-08-14 09:09:12,769: topic[/bebop/states/common/CommonState/BatteryStateChanged] removing connection to http://192.168.201.36:36960/
[rospy.internal][WARNING] 2017-08-14 09:09:15,182: Unknown error initiating TCP/IP socket to 192.168.201.36:36909 (http://192.168.201.36:35449/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-08-14 09:09:15,182: topic[/tf] removing connection to http://192.168.201.36:35449/
[rospy.internal][WARNING] 2017-08-14 09:09:15,183: Unknown error initiating TCP/IP socket to 192.168.201.36:36909 (http://192.168.201.36:35449/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-08-14 09:09:15,184: topic[/tf_static] removing connection to http://192.168.201.36:35449/
